#!/usr/bin/env python3
"""
Script to create/update a GitHub Gist with metrics data
"""

import os
import json
import requests
from datetime import datetime

GIST_TOKEN = os.environ.get('GITHUB_TOKEN')  # Fallback to GITHUB_TOKEN if GIST_TOKEN not set
GIST_ID = os.environ.get('GIST_ID')  # Optional: specify existing gist ID

def read_file(filename):
    """Read file content."""
    try:
        with open(filename, 'r') as f:
            return f.read()
    except FileNotFoundError:
        print(f"Warning: {filename} not found")
        return None

def create_or_update_gist():
    """Create a new gist or update existing one with metrics."""
    
    if not GIST_TOKEN:
        print("No GIST_TOKEN or GITHUB_TOKEN found. Skipping gist update.")
        return
    
    # Read all metric files
    json_content = read_file('github_metrics.json')
    csv_content = read_file('github_metrics.csv')
    html_content = read_file('github_metrics_report.html')
    
    if not any([json_content, csv_content, html_content]):
        print("No metric files found to upload")
        return
    
    # Prepare gist data
    files = {}
    
    if json_content:
        files['github_metrics.json'] = {'content': json_content}
    
    if csv_content:
        files['github_metrics.csv'] = {'content': csv_content}
    
    if html_content:
        files['github_metrics_report.html'] = {'content': html_content}
    
    # Add a README to the gist
    readme_content = f"""# 📊 GitHub Metrics - Live Dashboard

**Last Updated**: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC

This gist contains comprehensive GitHub metrics that are automatically updated every 6 hours.

## 📂 Files

- **github_metrics.json**: Complete metrics data in JSON format
- **github_metrics.csv**: Flattened metrics for spreadsheet analysis
- **github_metrics_report.html**: Interactive HTML dashboard (download and open in browser)

## 🔄 Auto-Update Schedule

These metrics are automatically updated:
- Every 6 hours via GitHub Actions
- On every push to the main branch
- Can be manually triggered via workflow dispatch

## 🌐 Live Access

View the live metrics dashboard at: [GitHub Pages URL]

---

Generated by [GitHub Metrics Tracker](https://github.com/amuzetnoM/amuzetnoM)
"""
    
    files['README.md'] = {'content': readme_content}
    
    gist_data = {
        'description': '📊 Live GitHub Metrics Dashboard - Auto-updated every 6 hours',
        'public': True,
        'files': files
    }
    
    headers = {
        'Authorization': f'token {GIST_TOKEN}',
        'Accept': 'application/vnd.github.v3+json'
    }
    
    try:
        if GIST_ID:
            # Update existing gist
            response = requests.patch(
                f'https://api.github.com/gists/{GIST_ID}',
                headers=headers,
                json=gist_data
            )
            if response.status_code == 200:
                gist = response.json()
                print(f"✅ Gist updated successfully: {gist['html_url']}")
                
                # Save gist ID for future updates
                with open('.gist_id', 'w') as f:
                    f.write(GIST_ID)
            else:
                print(f"❌ Failed to update gist: {response.status_code}")
                print(response.text)
        else:
            # Create new gist
            response = requests.post(
                'https://api.github.com/gists',
                headers=headers,
                json=gist_data
            )
            if response.status_code == 201:
                gist = response.json()
                gist_id = gist['id']
                print(f"✅ Gist created successfully: {gist['html_url']}")
                print(f"📌 Gist ID: {gist_id}")
                print(f"💡 To update this gist in future runs, set GIST_ID={gist_id} in your repository secrets")
                
                # Save gist ID for future updates
                with open('.gist_id', 'w') as f:
                    f.write(gist_id)
            else:
                print(f"❌ Failed to create gist: {response.status_code}")
                print(response.text)
    
    except Exception as e:
        print(f"❌ Error creating/updating gist: {e}")

if __name__ == '__main__':
    create_or_update_gist()
